CREATE TABLE IF NOT EXISTS chat_session (
  id UUID PRIMARY KEY,
  business_session_id VARCHAR(36) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_message (
  id UUID PRIMARY KEY,
  chat_session_id UUID NOT NULL REFERENCES chat_session(id) ON DELETE CASCADE,
  role VARCHAR(16) NOT NULL CHECK (role IN ('USER', 'ASSISTANT', 'SYSTEM')),
  content TEXT NOT NULL,
  risk_level VARCHAR(16) NOT NULL DEFAULT 'LOW',
  trace_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS llm_provider (
  id UUID PRIMARY KEY,
  name VARCHAR(128) NOT NULL UNIQUE,
  provider_type VARCHAR(64) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS llm_model (
  id UUID PRIMARY KEY,
  provider_id UUID NOT NULL REFERENCES llm_provider(id) ON DELETE CASCADE,
  name VARCHAR(128) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(provider_id, name)
);

CREATE TABLE IF NOT EXISTS prompt (
  id UUID PRIMARY KEY,
  name VARCHAR(128) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prompt_version (
  id UUID PRIMARY KEY,
  prompt_id UUID NOT NULL REFERENCES prompt(id) ON DELETE CASCADE,
  version INTEGER NOT NULL,
  template TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(prompt_id, version)
);

CREATE INDEX IF NOT EXISTS chat_message_session_created_idx ON chat_message(chat_session_id, created_at);
